### ISSUE TITLE
join us

### ISSUE THREAD

**Issue by hd-deman** [olmokramer/atom-linter-stylus#1]
You can transfer it to the AtomLinter org if you'd like. You'll still be the maintainer.
The sooner you do it, the less the statistics of downloads you will lose)
flow:
1. run `apm unpublish atom-linter-stylus` command to unpublish package
2. move repo to AtomLInter org (you will be an administrator)
3. fix repo url in package.json
4. publish again

This allows us to more easily keep track of linters that need to be fixed after major updates to the core linter. Additionally, by pulling you into the organization it allows us to keep linter creators up to date with changes and plans people have to advance the project. Lastly it has been a good tool when people have issues with the linters where users can rely on a larger stable of developers to help them with their issues on any given linter.

**Comment by olmokramer** [comment]
Sounds great! I'm not near my machine right now, but I'll get around to it tonight. Thanks!

**Comment by hd-deman** [comment]
good. also name it as `linter-stylus` while transfer it to the AtomLinter org.

**Comment by olmokramer** [comment]
I'm having problems unpublishing the package:

```
Unpublishing failed: Unauthorized
```

I really don't have time to deal with that right now, I'll get back to it this weekend.

**Comment by hd-deman** [comment]
ok. try `apm login` first

**Comment by olmokramer** [comment]
Yeah i did that. I messed a little with the repo a week ago, i think that's whats causing it. It'll have to be unpublished manually by the atom team i think

**Comment by hd-deman** [comment]
just a note: do not rename it before unpublish.

**Comment by olmokramer** [comment]
Hmmm.. now that there's [linter-stylint](https://atom.io/packages/linter-stylint) I'm thinking about discontinuing this package actually. stylint is much better
